name: Run Petstore Collection
on:
  push:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      # Install Newman and reporter
      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Run the Postman collection
      - name: Run Postman collection
        run: |
          newman run https://raw.githubusercontent.com/postman/openapi-samples/master/petstore/postman/petstore.postman_collection.json \
          -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme

      # Upload test results
      - name: Upload test results
        uses: actions/upload-artifact@v2.2.4  # or @v2.2.4 if @v3 fails
        with:
          name: TestResults
          path: testResults
