name: Run Petstore Collection
on:
  push:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository
      - uses: actions/checkout@v2

      # Set up Node.js
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      # Install Newman
      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Run the Petstore Collection (against local server, replace with your local URL)
      - name: Run Petstore collection
        run: |
          newman run https://raw.githubusercontent.com/postman/openapi-samples/master/petstore/postman/petstore.postman_collection.json \
          --env-var "baseUrl=http://localhost:3000" \
          -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme

      # Upload the test results
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: TestResults
          path: testResults
